-- Match and chat limits, with notifications when anything is removed.
--
-- Product rules (also documented in CLAUDE.md):
--   1. A user with 6 active chats (accepted, status active/chatting) gets no
--      new daily matches, and nobody can accept a 7th chat - checked for both
--      people in the pair.
--   2. A daily match that isn't turned into a chat within 24 hours expires.
--      It is removed from both users' Matches screens, both get a
--      'match_expired' notification saying why, and a replacement is
--      generated by the next hourly run of generate_daily_matches().
--   3. An accepted chat is removed for BOTH users as soon as EITHER user has
--      gone 48 hours without sending a message in it. Both get a
--      'chat_expired' notification saying whose inactivity closed it.
--
-- Before this migration: 1 was only enforced on generation for the user
-- being processed (not the candidate, not on accept); 2 hard-DELETEd rows
-- with no notification and only replaced them at the next 06:00 UTC run;
-- 3 used the pair-level matches.last_interaction_at, so a chat only closed
-- when BOTH people were silent.
--
-- Expired daily matches are now kept as status='expired' instead of being
-- deleted, so the generator can avoid re-suggesting the same person right
-- away and the notification can reference the match. They are purged after
-- 30 days. matches.updated_at has no maintenance trigger, so the cleanup
-- sets it explicitly when it closes a row; the rematch cooldown reads it.

-- ---------------------------------------------------------------------------
-- Notification types
-- ---------------------------------------------------------------------------
ALTER TABLE public.notifications
  DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE public.notifications
  ADD CONSTRAINT notifications_type_check
  CHECK (type IN ('new_match', 'chat_accepted', 'new_message', 'match_expired', 'chat_expired'));

-- ---------------------------------------------------------------------------
-- Limits
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.max_active_chats()
RETURNS integer
LANGUAGE sql
IMMUTABLE
AS $$ SELECT 6 $$;

CREATE OR REPLACE FUNCTION public.active_chat_count(p_user_id uuid)
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COUNT(*)::integer
  FROM public.matches
  WHERE (user_1 = p_user_id OR user_2 = p_user_id)
    AND status IN ('active', 'chatting')
    AND chat_request_status = 'accepted';
$$;

REVOKE ALL ON FUNCTION public.active_chat_count(uuid) FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- Per-user chat activity
-- ---------------------------------------------------------------------------
-- A user's last activity in a chat is their latest message, or the moment
-- the chat was accepted if they haven't sent one yet. accepted_at can't be
-- derived from last_interaction_at (every message bumps that), so it gets
-- its own column, maintained only by the guard trigger below.
ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS accepted_at timestamptz;

-- Existing chats start their 48h clock now rather than being judged
-- retroactively, so applying this migration doesn't close a wave of chats
-- nobody was warned about.
UPDATE public.matches
SET accepted_at = now()
WHERE chat_request_status = 'accepted'
  AND accepted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_messages_match_sender_created
  ON public.messages (match_id, sender_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Guard trigger on matches
-- ---------------------------------------------------------------------------
-- matches has an UPDATE policy with no column restriction (see
-- 20260917120000_mutual_photo_reveal.sql), so a participant can PATCH any
-- column directly. This trigger keeps the limit rules from being bypassed
-- that way:
--   * accepted_at is only ever set here, on the transition to 'accepted'
--   * expires_at can't be pushed back to dodge the 24h expiry
--   * a removed match (expired/inactive/skipped/...) can't be revived
--   * accepting is refused if either person already has 6 active chats
CREATE OR REPLACE FUNCTION public.guard_match_update()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.expires_at := OLD.expires_at;

  IF OLD.status NOT IN ('active', 'chatting')
     AND NEW.status IN ('active', 'chatting') THEN
    RAISE EXCEPTION 'match_closed';
  END IF;

  IF NEW.chat_request_status = 'accepted'
     AND OLD.chat_request_status IS DISTINCT FROM 'accepted' THEN
    -- Serialise concurrent accepts per user so two at once can't both see
    -- 5 chats and end at 7. user_1 < user_2 on every row, so the lock order
    -- is globally consistent and can't deadlock.
    PERFORM pg_advisory_xact_lock(hashtextextended('active_chats:' || NEW.user_1::text, 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('active_chats:' || NEW.user_2::text, 0));

    IF public.active_chat_count(NEW.user_1) >= public.max_active_chats()
       OR public.active_chat_count(NEW.user_2) >= public.max_active_chats() THEN
      RAISE EXCEPTION 'chat_limit_reached';
    END IF;

    NEW.accepted_at := now();
  ELSE
    NEW.accepted_at := OLD.accepted_at;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS guard_match_update_trigger ON public.matches;
CREATE TRIGGER guard_match_update_trigger
  BEFORE UPDATE ON public.matches
  FOR EACH ROW
  EXECUTE FUNCTION public.guard_match_update();

-- ---------------------------------------------------------------------------
-- Expiry + inactivity cleanup (hourly cron, and first step of generation)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.cleanup_expired_matches_and_inactive_chats()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Rule 2: daily matches not turned into a chat within 24 hours.
  WITH expired AS (
    UPDATE public.matches m
    SET status = 'expired', updated_at = now()
    WHERE m.status = 'active'
      AND COALESCE(m.chat_request_status, 'none') IN ('none', 'pending')
      AND m.expires_at < now()
    RETURNING m.id, m.user_1, m.user_2, m.chat_request_status, m.chat_request_sender
  ),
  recipients AS (
    SELECT e.id, e.user_1 AS user_id, e.user_2 AS other_id, e.chat_request_status, e.chat_request_sender
    FROM expired e
    UNION ALL
    SELECT e.id, e.user_2, e.user_1, e.chat_request_status, e.chat_request_sender
    FROM expired e
  )
  INSERT INTO public.notifications (user_id, type, title, message, match_id)
  SELECT
    r.user_id,
    'match_expired',
    'Match expired ⏳',
    CASE
      WHEN r.chat_request_status = 'pending' AND r.chat_request_sender = r.user_id THEN
        format('Your chat request to %s wasn''t accepted within 24 hours, so this match expired and was removed. A new match will be found for you.',
               COALESCE(p.nickname, 'your match'))
      WHEN r.chat_request_status = 'pending' THEN
        format('You didn''t respond to the chat request from %s within 24 hours, so this match expired and was removed. A new match will be found for you.',
               COALESCE(p.nickname, 'your match'))
      ELSE
        format('Neither you nor %s started a chat within 24 hours, so this match expired and was removed. A new match will be found for you.',
               COALESCE(p.nickname, 'your match'))
    END,
    r.id
  FROM recipients r
  LEFT JOIN public.profiles p ON p.id = r.other_id;

  -- Rule 3: accepted chats where either person has been silent for 48 hours.
  WITH activity AS (
    SELECT
      m.id,
      m.user_1,
      m.user_2,
      GREATEST(
        COALESCE(m.accepted_at, m.last_interaction_at, m.created_at),
        (SELECT MAX(msg.created_at) FROM public.messages msg
          WHERE msg.match_id = m.id AND msg.sender_id = m.user_1)
      ) AS user_1_last_active,
      GREATEST(
        COALESCE(m.accepted_at, m.last_interaction_at, m.created_at),
        (SELECT MAX(msg.created_at) FROM public.messages msg
          WHERE msg.match_id = m.id AND msg.sender_id = m.user_2)
      ) AS user_2_last_active
    FROM public.matches m
    WHERE m.chat_request_status = 'accepted'
      AND m.status IN ('active', 'chatting')
  ),
  stale AS (
    SELECT
      a.id,
      a.user_1_last_active < now() - INTERVAL '48 hours' AS user_1_idle,
      a.user_2_last_active < now() - INTERVAL '48 hours' AS user_2_idle
    FROM activity a
    WHERE a.user_1_last_active < now() - INTERVAL '48 hours'
       OR a.user_2_last_active < now() - INTERVAL '48 hours'
  ),
  removed AS (
    UPDATE public.matches m
    SET status = 'inactive', updated_at = now()
    FROM stale s
    WHERE m.id = s.id
      AND m.status IN ('active', 'chatting')
    RETURNING m.id, m.user_1, m.user_2, s.user_1_idle, s.user_2_idle
  ),
  recipients AS (
    SELECT r.id, r.user_1 AS user_id, r.user_2 AS other_id,
           r.user_1_idle AS me_idle, r.user_2_idle AS other_idle
    FROM removed r
    UNION ALL
    SELECT r.id, r.user_2, r.user_1, r.user_2_idle, r.user_1_idle
    FROM removed r
  )
  INSERT INTO public.notifications (user_id, type, title, message, match_id)
  SELECT
    rc.user_id,
    'chat_expired',
    'Chat closed 💤',
    CASE
      WHEN rc.me_idle AND rc.other_idle THEN
        format('Your chat with %s was closed because neither of you sent a message for 48 hours.',
               COALESCE(p.nickname, 'your match'))
      WHEN rc.me_idle THEN
        format('Your chat with %s was closed because you didn''t send a message for 48 hours. Chats close for both people when either one goes quiet for 48 hours.',
               COALESCE(p.nickname, 'your match'))
      ELSE
        format('Your chat with %s was closed because they didn''t send a message for 48 hours. Chats close for both people when either one goes quiet for 48 hours.',
               COALESCE(p.nickname, 'your match'))
    END,
    rc.id
  FROM recipients rc
  LEFT JOIN public.profiles p ON p.id = rc.other_id;

  -- Expired daily matches are only kept to stop immediate re-suggestion.
  -- Never purge anything that was a chat: messages cascade on delete.
  DELETE FROM public.matches
  WHERE status = 'expired'
    AND COALESCE(chat_request_status, 'none') <> 'accepted'
    AND expires_at < now() - INTERVAL '30 days';
END;
$$;

REVOKE ALL ON FUNCTION public.cleanup_expired_matches_and_inactive_chats() FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- Match generation
-- ---------------------------------------------------------------------------
-- Changes from 20260828143000_generate_daily_matches_exclude_blocked.sql
-- (scoring, compatibility, distance and block filters are unchanged):
--   * cleanup is delegated to cleanup_expired_matches_and_inactive_chats()
--   * the 6-chat limit is checked for the candidate too, not just the user
--   * the daily cap is now "at most 2 live matches at once AND at most 2
--     matches per 06:00-UTC day, not counting ones that expired". Expiry
--     frees a slot for a replacement; a skip or accepted chat does not.
--   * pairs whose match expired or whose chat closed in the last 7 days
--     aren't suggested to each other again
CREATE OR REPLACE FUNCTION public.generate_daily_matches()
RETURNS TABLE(matches_created integer, users_processed integer, users_skipped_chat_limit integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  user_record RECORD;
  potential_match RECORD;
  matches_created_count INTEGER := 0;
  users_processed_count INTEGER := 0;
  users_skipped_chat_limit_count INTEGER := 0;
  -- Match days roll over at 06:00 UTC, the long-standing "new matches
  -- arrive daily at 6 AM UTC" promise in the UI.
  today_start TIMESTAMP WITH TIME ZONE := date_trunc('day', now() - INTERVAL '6 hours') + INTERVAL '6 hours';
  today_end TIMESTAMP WITH TIME ZONE := today_start + INTERVAL '1 day';
  user_live_matches INTEGER;
  user_matches_today INTEGER;
  match_score_calc INTEGER;
  meme_overlap_count INTEGER;
  interest_overlap_count INTEGER;
  language_overlap_count INTEGER;
  prompt_overlap_count INTEGER;
  distance_km NUMERIC;
  cos_calc NUMERIC;
BEGIN
  PERFORM public.cleanup_expired_matches_and_inactive_chats();

  FOR user_record IN
    SELECT uo.user_id, uo.mood, uo.selected_memes, p.city, p.region, p.country,
           p.gender, p.sexual_orientation, p.interested_in, p.latitude, p.longitude,
           p.max_distance_preference, p.min_age_preference, p.max_age_preference, p.age,
           p.interests, p.languages_spoken, p.personality_prompts
    FROM public.user_onboarding uo
    JOIN public.profiles p ON uo.user_id = p.id
    WHERE uo.mood IS NOT NULL
      AND uo.mood != 'pending_daily_update'
      AND uo.selected_memes IS NOT NULL
      AND NOT (array_length(uo.selected_memes, 1) = 1 AND uo.selected_memes[1] = 'pending')
      AND uo.perfect_sunday IS NOT NULL
      AND uo.perfect_sunday != 'pending_daily_update'
      AND array_length(uo.selected_memes, 1) > 0
      AND p.is_profile_complete = true
      AND p.gender IS NOT NULL
      AND p.sexual_orientation IS NOT NULL
      AND p.interested_in IS NOT NULL
  LOOP
    users_processed_count := users_processed_count + 1;

    IF public.active_chat_count(user_record.user_id) >= public.max_active_chats() THEN
      users_skipped_chat_limit_count := users_skipped_chat_limit_count + 1;
      CONTINUE;
    END IF;

    SELECT
      COUNT(*) FILTER (
        WHERE status = 'active'
          AND COALESCE(chat_request_status, 'none') IN ('none', 'pending')
          AND expires_at > now()
      ),
      COUNT(*) FILTER (
        WHERE matched_on >= today_start
          AND matched_on < today_end
          AND status <> 'expired'
      )
    INTO user_live_matches, user_matches_today
    FROM public.matches
    WHERE user_1 = user_record.user_id OR user_2 = user_record.user_id;

    IF user_live_matches >= 2 OR user_matches_today >= 2 THEN
      CONTINUE;
    END IF;

    FOR potential_match IN
      SELECT DISTINCT ON (uo2.user_id)
             uo2.user_id, uo2.mood, uo2.selected_memes, pr2.city, pr2.region, pr2.country,
             pr2.gender, pr2.sexual_orientation, pr2.interested_in, pr2.latitude, pr2.longitude,
             pr2.max_distance_preference, pr2.min_age_preference, pr2.max_age_preference, pr2.age,
             pr2.interests, pr2.languages_spoken, pr2.personality_prompts
      FROM public.user_onboarding uo2
      JOIN public.profiles pr2 ON uo2.user_id = pr2.id
      WHERE uo2.user_id != user_record.user_id
        AND uo2.mood IS NOT NULL
        AND uo2.mood != 'pending_daily_update'
        AND uo2.selected_memes IS NOT NULL
        AND NOT (array_length(uo2.selected_memes, 1) = 1 AND uo2.selected_memes[1] = 'pending')
        AND uo2.perfect_sunday IS NOT NULL
        AND uo2.perfect_sunday != 'pending_daily_update'
        AND array_length(uo2.selected_memes, 1) > 0
        AND pr2.is_profile_complete = true
        AND pr2.gender IS NOT NULL
        AND pr2.sexual_orientation IS NOT NULL
        AND pr2.interested_in IS NOT NULL
        -- Skip pairs that are already matched, or whose match expired / chat
        -- closed recently - a "replacement" must be someone new.
        AND NOT EXISTS (
          SELECT 1
          FROM public.matches mx
          WHERE (
            (mx.user_1 = user_record.user_id AND mx.user_2 = uo2.user_id)
            OR
            (mx.user_1 = uo2.user_id AND mx.user_2 = user_record.user_id)
          )
          AND (
            mx.status IN ('active', 'chatting')
            OR (mx.status IN ('expired', 'inactive') AND mx.updated_at > now() - INTERVAL '7 days')
          )
        )
        AND NOT EXISTS (
          SELECT 1 FROM public.blocked_users bu
          WHERE (bu.blocker_id = user_record.user_id AND bu.blocked_id = uo2.user_id)
             OR (bu.blocker_id = uo2.user_id AND bu.blocked_id = user_record.user_id)
        )
        -- Gender/interest compatibility
        AND (
          (user_record.interested_in = 'men' AND pr2.gender = 'male') OR
          (user_record.interested_in = 'women' AND pr2.gender = 'female') OR
          (user_record.interested_in = 'non_binary' AND pr2.gender = 'non_binary') OR
          (user_record.interested_in = 'everyone')
        )
        AND (
          (pr2.interested_in = 'men' AND user_record.gender = 'male') OR
          (pr2.interested_in = 'women' AND user_record.gender = 'female') OR
          (pr2.interested_in = 'non_binary' AND user_record.gender = 'non_binary') OR
          (pr2.interested_in = 'everyone')
        )
        -- Age preferences
        AND pr2.age >= user_record.min_age_preference
        AND pr2.age <= user_record.max_age_preference
        AND user_record.age >= pr2.min_age_preference
        AND user_record.age <= pr2.max_age_preference
      ORDER BY uo2.user_id, RANDOM()
      LIMIT 30
    LOOP
      -- Distance check
      IF user_record.latitude IS NOT NULL
         AND user_record.longitude IS NOT NULL
         AND potential_match.latitude IS NOT NULL
         AND potential_match.longitude IS NOT NULL THEN
        BEGIN
          cos_calc := cos(radians(user_record.latitude)) *
                     cos(radians(potential_match.latitude)) *
                     cos(radians(potential_match.longitude) - radians(user_record.longitude)) +
                     sin(radians(user_record.latitude)) *
                     sin(radians(potential_match.latitude));

          cos_calc := GREATEST(-1, LEAST(1, cos_calc));
          distance_km := 6371 * acos(cos_calc);

          IF distance_km > user_record.max_distance_preference
             OR distance_km > potential_match.max_distance_preference THEN
            CONTINUE;
          END IF;
        EXCEPTION WHEN OTHERS THEN
          IF user_record.country != potential_match.country THEN
            CONTINUE;
          END IF;
        END;
      ELSE
        IF user_record.country != potential_match.country THEN
          CONTINUE;
        END IF;
      END IF;

      match_score_calc := 0;

      IF user_record.mood = potential_match.mood THEN
        match_score_calc := match_score_calc + 25;
      END IF;

      SELECT COUNT(*) INTO meme_overlap_count
      FROM unnest(user_record.selected_memes) AS meme1
      WHERE meme1 = ANY(potential_match.selected_memes);

      match_score_calc := match_score_calc + LEAST(meme_overlap_count * 10, 40);

      SELECT COUNT(*) INTO interest_overlap_count
      FROM unnest(COALESCE(user_record.interests, '{}'::text[])) AS interest1
      WHERE interest1 = ANY(COALESCE(potential_match.interests, '{}'::text[]));

      match_score_calc := match_score_calc + LEAST(interest_overlap_count * 5, 20);

      SELECT COUNT(*) INTO language_overlap_count
      FROM unnest(COALESCE(user_record.languages_spoken, '{}'::text[])) AS lang1
      WHERE lang1 = ANY(COALESCE(potential_match.languages_spoken, '{}'::text[]));

      match_score_calc := match_score_calc + LEAST(language_overlap_count * 5, 10);

      SELECT COUNT(*) INTO prompt_overlap_count
      FROM jsonb_object_keys(COALESCE(user_record.personality_prompts, '{}'::jsonb)) AS key1
      WHERE key1 IN (
        SELECT jsonb_object_keys(COALESCE(potential_match.personality_prompts, '{}'::jsonb))
      );

      match_score_calc := match_score_calc + LEAST(prompt_overlap_count * 5, 5);

      match_score_calc := LEAST(match_score_calc, 100);

      IF match_score_calc >= 30 THEN
        -- The candidate must be under both limits too.
        IF public.active_chat_count(potential_match.user_id) >= public.max_active_chats() THEN
          CONTINUE;
        END IF;

        SELECT
          COUNT(*) FILTER (
            WHERE status = 'active'
              AND COALESCE(chat_request_status, 'none') IN ('none', 'pending')
              AND expires_at > now()
          ),
          COUNT(*) FILTER (
            WHERE matched_on >= today_start
              AND matched_on < today_end
              AND status <> 'expired'
          )
        INTO user_live_matches, user_matches_today
        FROM public.matches
        WHERE user_1 = potential_match.user_id OR user_2 = potential_match.user_id;

        IF user_live_matches >= 2 OR user_matches_today >= 2 THEN
          CONTINUE;
        END IF;

        BEGIN
          INSERT INTO public.matches (
            user_1, user_2, matched_on, expires_at, match_score, status, chat_request_status
          ) VALUES (
            LEAST(user_record.user_id, potential_match.user_id),
            GREATEST(user_record.user_id, potential_match.user_id),
            now(),
            now() + INTERVAL '24 hours',
            match_score_calc,
            'active',
            'none'
          );

          matches_created_count := matches_created_count + 1;

          SELECT
            COUNT(*) FILTER (
              WHERE status = 'active'
                AND COALESCE(chat_request_status, 'none') IN ('none', 'pending')
                AND expires_at > now()
            ),
            COUNT(*) FILTER (
              WHERE matched_on >= today_start
                AND matched_on < today_end
                AND status <> 'expired'
            )
          INTO user_live_matches, user_matches_today
          FROM public.matches
          WHERE user_1 = user_record.user_id OR user_2 = user_record.user_id;

          IF user_live_matches >= 2 OR user_matches_today >= 2 THEN
            EXIT;
          END IF;
        EXCEPTION WHEN unique_violation THEN
          CONTINUE;
        END;
      END IF;
    END LOOP;
  END LOOP;

  RETURN QUERY SELECT matches_created_count, users_processed_count, users_skipped_chat_limit_count;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Schedules
-- ---------------------------------------------------------------------------
-- cron.schedule() upserts by job name. Generation now runs hourly (10 min
-- after cleanup) so an expired match is replaced within the hour; the
-- per-day cap above still limits users to 2 fresh matches per 06:00-UTC day.
SELECT cron.schedule(
  'cleanup-expired-matches-db',
  '0 * * * *',
  $$SELECT public.cleanup_expired_matches_and_inactive_chats();$$
);

SELECT cron.schedule(
  'generate-daily-matches-db',
  '10 * * * *',
  $$SELECT public.generate_daily_matches();$$
);
